title: Climate Change AI
description: Tackling Climate Change with Machine Learning
theme: jekyll-theme-cayman
google_analytics: UA-142136893-1
exclude:
  - vendor
  - resources_content.md
  - raw_workshop_files
plugins:
  - jekyll-redirect-from
paper_url: https://arxiv.org/pdf/1906.05433.pdf
forum_url: https://forum.climatechange.ai
